[package]
name = "gfx-backend-dx12"
version = "0.1.0"
description = "DirectX-12 API backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx-backend-dx12"
workspace = "../../.."

[features]
default = ["winit"]

[lib]
name = "gfx_backend_dx12"

[dependencies]
bitflags = "1.0"
log = "0.3"
gfx-hal = { path = "../../hal", version = "0.1" }
d3d12-sys = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
d3dcompiler-sys = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
dxgi-sys = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
dxguid-sys = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
kernel32-sys = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
spirv_cross = "0.4.1"
user32-sys = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
winapi = { git = "https://github.com/msiglreith/winapi-rs.git", branch = "gfx" }
winit = { version = "0.7", optional = true }
wio = { git = "https://github.com/msiglreith/wio-rs.git", branch = "stable" }
smallvec = "0.4"
