sudo: false
language: rust
cache:
  directories:
   - $HOME/.cargo
before-cache:
  - rm -rf $HOME/.cargo/registry

matrix:
  include:
    # Linux 64bit
    - os: linux
      rust: stable
      compiler: gcc
    - os: linux
      rust: nightly
      compiler: gcc

    # macOS 64bit
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      rust: stable
      osx_image: xcode9.4
      compiler: clang
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      rust: nightly
      osx_image: xcode9.4
      compiler: clang

    # iPhoneOS 64bit
    - env: TARGET=aarch64-apple-ios
      os: osx
      osx_image: xcode9.4
      rust: nightly

    # Windows 64bit
    - os: windows
      rust: stable

    # WebAssembly
    - env: WASM=1
      os: linux
      rust: nightly
      compiler: gcc

  allow_failures: # temp
    - env: WASM=1

branches:
  except:
    - staging.tmp

before_install:
  # Do not run bors builds against the nightly compiler.
  # We want to find out about nightly bugs, so they're done in master, but we don't block on them.
  - if [[ $TRAVIS_RUST_VERSION == "nightly" && $TRAVIS_BRANCH == "staging" ]]; then exit; fi
  - rustup self update
  - rustup target add $TARGET; true
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-5; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install make mingw && rustup component remove rust-mingw && for i in crt2.o dllcrt2.o libmingwex.a libmsvcrt.a; do cp -f "/C/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/$i" "`rustc --print sysroot`/lib/rustlib/x86_64-pc-windows-gnu/lib"; done; fi
  - if [[ -n "$WASM" ]]; then rustup target add wasm32-unknown-unknown --toolchain nightly && cargo install -f wasm-bindgen-cli; fi

addons:
  apt:
    sources:
      # install a newer cmake since at this time Travis only has version 2.8.7
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
      #- ppa:xorg-edgers/ppa # for libosmesa6-dev
    packages:
      - xdotool
      - cmake
      - cmake-data
      - libxxf86vm-dev
      - libxinerama-dev
      - libxinerama1
      - libxcursor-dev
      - libxcursor1
      - libglfw-dev
      - libosmesa6-dev
      - libxi-dev
      - libxrandr-dev
      - g++-5
      - gcc

script:
  - if [[ $TRAVIS_RUST_VERSION == "nightly" && $TRAVIS_BRANCH == "staging" ]]; then exit; fi
  - export PATH=$PATH:$HOME/deps/bin
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export LIBRARY_PATH=$HOME/deps/usr/lib/x86_64-linux-gnu; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export LD_LIBRARY_PATH=$LIBRARY_PATH; fi
  - if [[ $TARGET != "aarch64-apple-ios" ]]; then make all; else make check; fi
  - if [[ -n "$WASM" ]]; then make quad-wasm; fi
  #- if [[ $TRAVIS_OS_NAME == "linux" ]]; then make reftests-ci; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then cd src/backend/metal && cargo check --all-features; fi
