sudo: false
language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - linux
  - osx
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7479b6691b7e5e40716a
    on_success: always
    on_failure: always
    on_start: false
before_install:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake; fi
addons:
  apt:
    sources:
      # install a newer cmake since at this time Travis only has version 2.8.7
      - george-edison55-precise-backports
      # add a repository for libsdl2-dev (enable sudo before uncommenting this)
      #- sourceline: 'ppa:zoogie/sdl2-snapshots'
    packages:
      - xdotool
      - cmake
      - cmake-data
      - libxxf86vm-dev
      - libxinerama-dev
      - libxinerama1
      - libxcursor-dev
      - libxcursor1
      #- libsdl2-dev
      - libglfw-dev
script:
  - export RUST_BACKTRACE=1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo build --features vulkan; else cargo build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --features metal; else cargo build; fi
  - cargo test -p gfx_core
  - cargo test -p gfx
  - cargo test -p gfx_device_gl
  - cargo test -p gfx_window_glutin
  - cargo test -p gfx_window_glfw
  #- cargo test -p gfx_window_sdl
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo test --features vulkan; cargo test -p gfx_device_vulkan --features vulkan; cargo test -p gfx_window_vulkan --features vulkan; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo test --features metal; cargo test -p gfx_device_metal --features metal; cargo test -p gfx_window_metal --features metal; fi
