environment:
  matrix:
    - TARGET: 1.9.0-x86_64-pc-windows
      COMPILER: gnu
    - TARGET: 1.9.0-x86_64-pc-windows
      COMPILER: msvc
    - TARGET: nightly-x86_64-pc-windows
      COMPILER: msvc
install:
  - if %COMPILER%==gnu choco install -y mingw
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}-${env:COMPILER}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin;C:\tools\mingw64\bin"
  - if %COMPILER%==gnu gcc -v
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build
test_script:
  - cargo test -p gfx_core
  - cargo test -p gfx
  - cargo test -p gfx_device_dx11
  - cargo test -p gfx_window_dxgi
  - cargo test -p gfx_device_gl
  - cargo test -p gfx_window_glutin
  - cargo test
