[package]
name = "gfx_app"
version = "0.6.0"
description = "GFX example application framework"
homepage = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
documentation = "https://docs.rs/gfx_app"

[features]
default = []
mint = ["gfx/mint", "gfx_core/mint"]
metal = ["gfx_device_metal", "gfx_window_metal"]
vulkan = ["gfx_device_vulkan", "gfx_window_vulkan"]
glfw = ["gfx_window_glfw"]
sdl = ["gfx_window_sdl"]
serialize = ["gfx/serialize", "gfx_core/serialize"]
headless = ["gfx_window_glutin/headless"]
unstable = []

[lib]
name = "gfx_app"

[dependencies]
log = "0.4"
env_logger = "0.5"
glutin = "0.17"
winit = "0.16"
gfx_core = { path = "src/core", version = "0.8" }
gfx = { path = "src/render", version = "0.17" }
gfx_macros = { path = "src/macros", version = "0.2" }
gfx_device_gl = { path = "src/backend/gl", version = "0.16" }
gfx_window_glutin = { path = "src/window/glutin", version = "0.24" }
gfx_window_glfw = { path = "src/window/glfw", version = "0.17", optional = true }
gfx_window_sdl = { path = "src/window/sdl", version = "0.9", optional = true }

[dependencies.gfx_device_vulkan]
path = "src/backend/vulkan"
version = "0.2"
optional = true

[dependencies.gfx_window_vulkan]
path = "src/window/vulkan"
version = "0.7"
optional = true

[dependencies.gfx_device_metal]
path = "src/backend/metal"
version = "0.3"
optional = true

[dependencies.gfx_window_metal]
path = "src/window/metal"
version = "0.7"
optional = true

[target.'cfg(windows)'.dependencies]
gfx_device_dx11 = { path = "src/backend/dx11", version = "0.7" }
gfx_window_dxgi = { path = "src/window/dxgi", version = "0.15" }

[[example]]
name = "blend"
path = "examples/blend/main.rs"

[[example]]
name = "cube"
path = "examples/cube/main.rs"

[[example]]
name = "deferred"
path = "examples/deferred/main.rs"

[[example]]
name = "flowmap"
path = "examples/flowmap/main.rs"

[[example]]
name = "gamma"
path = "examples/gamma/main.rs"

[[example]]
name = "performance"
path = "examples/performance/main.rs"

[[example]]
name = "shadow"
path = "examples/shadow/main.rs"

[[example]]
name = "skybox"
path = "examples/skybox/main.rs"

[[example]]
name = "terrain"
path = "examples/terrain/main.rs"

[[example]]
name = "terrain_tessellated"
path = "examples/terrain_tessellated/main.rs"

[[example]]
name = "triangle"
path = "examples/triangle/main.rs"

[[example]]
name = "instancing"
path = "examples/instancing/main.rs"

[[example]]
name = "ubo_tilemap"
path = "examples/ubo_tilemap/main.rs"

[[example]]
name = "mipmap"
path = "examples/mipmap/main.rs"

[[example]]
name = "particle"
path = "examples/particle/main.rs"

[[example]]
name = "render_target"
path = "examples/render_target/main.rs"

[dev-dependencies]
cgmath = "0.16"
gfx_gl = "0.5"
rand = "0.4"
genmesh = "0.5"
noise = "0.2" #TODO: update
image = "0.19"
