# Copyright 2014 The Gfx-rs Developers.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "gfx"
version = "0.1.0"
description = "A high-performance, bindless graphics API"
homepage = "https://github.com/gfx/gfx-rs"
repository = "https://github.com/gfx/gfx-rs"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]

[lib]
name = "gfx"
path = "src/gfx/lib.rs"

[dependencies]
log = "*"
time = "*"

[dependencies.gfx_macros]
path = "src/gfx_macros"
plugin = true

[dependencies.gfx_device_gl]
path = "src/device"

[dev_dependencies]
glfw = "*"
cgmath = "*"
genmesh = "*"
gfx_gl = "*"
noise = "*"
#glutin = "*"

[[example]]
name = "cube"
path = "examples/cube/main.rs"

[[example]]
name = "terrain"
path = "examples/terrain/main.rs"

[[example]]
name = "deferred"
path = "examples/deferred/main.rs"

#[[example]]
#name = "glutin"
#path = "examples/glutin/main.rs"

[[example]]
name = "performance"
path = "examples/performance/main.rs"

[[example]]
name = "triangle"
path = "examples/triangle/main.rs"
