[package]
name = "gfx_meta"
version = "0.0.1"
description = "Meta package for GFX"
homepage = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]

[lib]
name = "gfx_meta"

[dependencies.gfx]
path = "src/core"
version = "0.6"

[dependencies.gfx_device_gl]
path = "src/backend/gl"
version = "0.4"

[dependencies.gfx_window_glfw]
path = "src/window/glfw"
version = "0.2"
