[package]
name = "gfx_meta"
version = "0.0.1"
description = "Meta package for GFX"
homepage = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]

[features]
unstable = []


[lib]
name = "gfx_meta"

[dependencies]
gfx_core = { path = "src/render", version = "0.1" }
gfx_device_gl = { path = "src/backend/gl", version = "0.8" }
gfx_window_glutin = { path = "src/window/glutin", version = "0.9" }
gfx_window_glfw = { path = "src/window/glfw", version = "0.7" }
gfx = { path = "src/render", version = "0.9" }


[[example]]
name = "blend"
path = "examples/blend/main.rs"

[[example]]
name = "cube"
path = "examples/cube/main.rs"

[[example]]
name = "deferred"
path = "examples/deferred/main.rs"

[[example]]
name = "flowmap"
path = "examples/flowmap/main.rs"

[[example]]
name = "performance"
path = "examples/performance/main.rs"

[[example]]
name = "shadow"
path = "examples/shadow/main.rs"

[[example]]
name = "terrain"
path = "examples/terrain/main.rs"

[[example]]
name = "triangle"
path = "examples/triangle/main.rs"

[[example]]
name = "instancing"
path = "examples/instancing/main.rs"

[[example]]
name = "ubo_tilemap"
path = "examples/ubo_tilemap/main.rs"

[[example]]
name = "mipmap"
path = "examples/mipmap/main.rs"

[dev_dependencies]
env_logger = "*"
log = "*"
cgmath = "0.3"
glutin = ">=0.4.2"
glfw = "0.3"
gfx_gl = "0.1"
rand = "*"
time = "*"
genmesh = "*"
noise = "*"
image = "*"
