[package]

name = "example-cube"
version = "0.1.0"
authors = [
]

[[bin]]
name = "cube"
path = "main.rs"

[dependencies.gfx]
path = "../../../"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.cgmath]
git = "http://github.com/bjz/cgmath-rs"
