[package]
name = "gfx_device_metalll"
version = "0.1.0"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]

[features]
default = []
native_heap = []
native_fence = []

[dependencies]
log = "0.3"
gfx_corell = { path = "../../corell", version = "0.1.0" }
winit = "0.6"
cocoa = "0.5.0"
objc = "0.2"
metal-rs = "0.3"
io-surface = "0.7"
core-foundation = "0.3"
core-graphics = "0.7"
scopeguard = "0.3"
block = "0.1"

