# Copyright 2016 The Gfx-rs Developers.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "gfx"
version = "0.16.1"
description = "A high-performance, bindless graphics API"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "../../README.md"
documentation = "https://docs.rs/gfx"
categories = ["rendering::graphics-api"]

[lib]
name = "gfx"
path = "src/lib.rs"

[features]
cgmath-types = ["gfx_core/cgmath-types", "cgmath"]
serialize = ["gfx_core/serialize", "draw_state/serialize"]
unstable = []

[dependencies]
cgmath = { version = "0.14", optional = true }
derivative = "1.0"
draw_state = "0.7"
gfx_core = { path = "../core", version = "0.7.1" }
log = "0.3"
