[package]
name = "gfx_window_glutin"
version = "0.17.0"
description = "Glutin window for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx_window_glutin"
workspace = "../../.."

[lib]
name = "gfx_window_glutin"

[dependencies]
glutin = "0.9"
gfx_core = { path = "../../core", version = "0.7" }
gfx_device_gl = { path = "../../backend/gl", version = "0.14" }

[features]
headless = []
