[package]
name = "gfx_device_metal"
version = "0.3.0"
description = "Metal backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx_device_metal"
workspace = "../../.."

[lib]
name = "gfx_device_metal"

[dependencies]
log = "0.3"
gfx_core = { path = "../../core", version = "0.7" }
cocoa = "0.9"
libc = "0.2"
objc = "0.2"
objc-foundation = "0.1"
bit-set = "0.4"
metal-rs = "0.4"
block = "0.1"
