[package]
name = "gfx-backend-metal"
version = "0.1.0"
description = "Metal API backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx-backend-metal"
workspace = "../../.."

[features]
default = ["winit"]
metal_default_capture_scope=[]

[lib]
name = "gfx_backend_metal"

[dependencies]
gfx-hal = { path = "../../hal", version = "0.1" }
log = "0.4"
winit = { version = "0.13", optional = true }
metal-rs = "0.10.1"
foreign-types = "0.3"
objc = "0.2"
block = "0.1"
cocoa = "0.15"
core-foundation = "0.6"
core-graphics = "0.14"
io-surface = "0.10"
smallvec = "0.6"
spirv_cross = "0.9"
