[package]
name = "gfx-backend-metal"
version = "0.2.0"
description = "Metal API backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "MIT OR Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx-backend-metal"
workspace = "../../.."
edition = "2018"

[features]
default = ["winit"]
auto-capture = []

[lib]
name = "gfx_backend_metal"

[dependencies]
hal = { path = "../../hal", version = "0.2", package = "gfx-hal" }
range-alloc = { path = "../../auxil/range-alloc", version = "0.1" }
arrayvec = "0.4"
bitflags = "1.0"
copyless = "0.1"
log = { version = "0.4" }
winit = { version = "0.19", optional = true }
dispatch = { version = "0.1", optional = true }
metal = { version = "0.14.0", features = ["private"] }
foreign-types = "0.3"
objc = "0.2.5"
block = "0.1"
cocoa = "0.18"
core-graphics = "0.17"
smallvec = "0.6"
spirv_cross = { git = "https://github.com/grovesNL/spirv_cross", features = ["msl"] }
parking_lot = "0.6.3"
storage-map = "0.1.2"
