[package]
name = "gfx_backend_metal"
version = "0.1.0"
description = "Metal API backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx_backend_metal"
workspace = "../../.."

[features]
default = []
argument_buffer = []

[lib]
name = "gfx_backend_metal"

[dependencies]
gfx_core = { path = "../../core", version = "0.10" }
log = "0.3"
winit = "0.7"
scopeguard = "0.3"
metal-rs = "0.4"
objc = "0.2"
block = "0.1"
cocoa = "0.9"
core-foundation = "0.3"
core-graphics = "0.9"
io-surface = "0.7"
